spring:
    profiles:
      active: prod

    jta:
      enabled: true
      service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
      max-actives: 200
      enable-logging: false

      atomikos:
        datasource:
          posmall:
            unique-resource-name: dataSourcePosmall
            max-pool-size: 5
            min-pool-size: 1
            max-life-time: 20000
            borrow-connection-timeout: 10000
            xa-data-source-class-name: com.tmax.tibero.jdbc.ext.TbXADataSource
            xa-properties:
              user: posmall
              password: posmall
              URL: jdbc:tibero:thin:@192.168.100.136:8629:tibero

          webcache:
            unique-resource-name: dataSourceWebcache
            max-pool-size: 5
            min-pool-size: 1
            max-life-time: 20000
            borrow-connection-timeout: 10000
#            xa-data-source-class-name: com.microsoft.sqlserver.jdbc.SQLServerXADataSource
            xa-data-source-class-name : com.mysql.cj.jdbc.MysqlXADataSource
            xa-properties:
              user: root
              password: wofl07
              URL: jdbc:mysql://localhost:3306/world?serverTimezone=UTC&useSSL=false
#              URL: jdbc:sqlserver://210.103.25.151:1433;databaseName=iTMSNTData
server:
  port: 8090
